---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: wego-github-tmp-install
  namespace: wego-system
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: wego-github-tmp-install
  url: ssh://git@github.com/sympatheticmoose/tmp-install.git

